[tools]
helm = "4.2.3"
python = "3.14.7"
terraform = "1.15.8"
duckdb = "1.5.5"
aws-cli = "2.36.17"
kind = "0.32.0"
github-cli = "2.97.0"
jq = "1.8.2"
kustomize = "5.8.1"
k9s = "0.51.0"

# docker関連
docker-cli = "29.7.2"
docker-compose = "5.4.0"
colima = "0.10.3"
lima = "2.2.0" # colimaの依存パッケージ
