[tools]
helm = "4.2.4"
python = "3.14.7"
terraform = "1.16.1"
duckdb = "1.5.5"
aws-cli = "2.36.39"
kind = "0.33.0"
github-cli = "2.99.0"
jq = "1.8.2"
kustomize = "5.8.1"
k9s = "0.51.0"
neovim = "0.12.5"

# docker関連
docker-cli = "29.7.2"
docker-compose = "5.5.0"
colima = "0.10.3"
lima = "2.2.0" # colimaの依存パッケージ
